import Head from 'next/head';
import React from "react";

import useContacts from "../hooks/useContacts";
import ContactList from "../components/ContactList";

import styles from '../styles/Home.module.css';

function Home() {
  const { contacts, addContact, updateContact, deleteContact } = useContacts();

  return (
    <div>
      <Head>
        <title>Contact List</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <ContactList contacts={contacts} onEdit={updateContact} onDelete={deleteContact} />
      </main>
    </div>
  );
}

export default Home;
