import Head from 'next/head';

import ContactList from "../components/ContactList";

import styles from '../styles/Home.module.css';

function Home() {
  return (
    <div>
      <Head>
        <title>Contact List</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>
          Contacts
        </h1>
        <ContactList />
      </main>
    </div>
  );
}

export default Home;
